// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function GetTableInfo(arg1) {
  return window['go']['main']['App']['GetTableInfo'](arg1);
}

export function GetTableRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableRows'](arg1, arg2, arg3);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDB(arg1) {
  return window['go']['main']['App']['OpenDB'](arg1);
}

export function SelectDbFile() {
  return window['go']['main']['App']['SelectDbFile']();
}
