// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AddToRecent(arg1:string,arg2:string):Promise<void>;

export function Close():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<db.QueryResult>;

export function GetRecentDBs():Promise<Array<db.RecentDB>>;

export function GetTableInfo(arg1:string):Promise<db.TableInfo>;

export function GetTableRows(arg1:string,arg2:db.Cursor,arg3:number):Promise<db.TableRows>;

export function GetTables():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDB(arg1:string):Promise<void>;

export function SelectDbFile():Promise<string>;
